version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 18888:18888
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server